In [1]:
import torch
import torch.nn as nn

class CustomLayer(nn.Module):
    def __init__(self, n_features):
        super(CustomLayer, self).__init__()
        self.n_features = n_features
        # Initialize the interaction tensor as a learnable parameter
        self.interaction_tensor = nn.Parameter(torch.randn(n_features, n_features, n_features))

    def forward(self, x):
        # x is expected to be of size [batch, length, n_features]
        batch, length, n_features = x.size()

        # Process each [n_features] vector across batch and length
        output = x.new_empty(batch, length, n_features)
        for b in range(batch):
            for l in range(length):
                state_tensor = x[b, l, :]  # Shape: [n_features]
                # Step 1: Multiply state tensor by interaction tensor to get transition tensor
                # We manually implement the multiplication to match your operation
                transition_tensor = torch.einsum('i,ijk->jk', state_tensor, self.interaction_tensor)
                # Step 2: Multiply the transition tensor by the state tensor
                # Resulting shape: [n_features]
                output[b, l, :] = torch.matmul(transition_tensor, state_tensor)

        return output


In [2]:
import torch
import torch.nn as nn

class CustomLayerVectorized(nn.Module):
    def __init__(self, n_features):
        super(CustomLayerVectorized, self).__init__()
        self.n_features = n_features
        # Initialize the interaction tensor as a learnable parameter
        self.interaction_tensor = nn.Parameter(torch.randn(n_features, n_features, n_features))

    def forward(self, x):
        # x is expected to be of size [batch, length, n_features]
        batch, length, n_features = x.size()

        # Pre-allocate output tensor
        output = x.new_empty(batch, length, n_features)

        # Loop over length, but vectorize over the batch
        for l in range(length):
            # Extract all vectors at position l across all batches
            state_tensor = x[:, l, :]  # Shape: [batch, n_features]
            
            # Vectorized operation for all batches
            # Step 1: Calculate the transition tensor
            # Since we cannot directly use einsum for batched operation in this specific scenario,
            # we manually broadcast and multiply to achieve the intended result.
            # This involves expanding dimensions to enable broadcasting.
            state_tensor_expanded = state_tensor.unsqueeze(1).expand(-1, n_features, -1)  # Shape: [batch, n_features, n_features]
            interaction_tensor_expanded = self.interaction_tensor.unsqueeze(0).expand(batch, -1, -1, -1)  # Shape: [batch, n_features, n_features, n_features]
            # Multiply and sum over the last dimension to get the transition tensor
            transition_tensor = torch.einsum('bik,bijk->bij', state_tensor_expanded, interaction_tensor_expanded)
            
            # Step 2: Multiply the transition tensor by the state tensor to get the output
            output[:, l, :] = torch.einsum('bij,bj->bi', transition_tensor, state_tensor)

        return output



In [3]:
# n_features = 16
# batch, length, dim = 2, 64, n_features
# x = torch.randn(batch, length, dim)
# model = CustomLayerVectorized(
#     n_features = n_features
# )
# y = model(x)

# print(x.shape)
# assert y.shape == x.shape

In [4]:
import torch

def torch_randnorm(size, dim=0):
    # Generate a random tensor
    rand_tensor = torch.rand(size)
    
    # Normalize along the specified dimension
    sum_along_dim = torch.sum(rand_tensor, dim=dim, keepdim=True)
    normalized_tensor = rand_tensor / sum_along_dim
    
    return normalized_tensor

# Example usage
normalized_tensor = torch_randnorm([5,6], dim=1)
print(normalized_tensor)
print(normalized_tensor.sum(dim=1))

tensor([[0.2689, 0.0689, 0.1848, 0.0131, 0.3404, 0.1239],
        [0.2006, 0.1680, 0.0602, 0.0144, 0.3262, 0.2306],
        [0.2770, 0.1307, 0.0917, 0.0989, 0.2853, 0.1164],
        [0.1350, 0.1396, 0.1291, 0.1483, 0.3212, 0.1268],
        [0.2361, 0.3043, 0.0822, 0.3354, 0.0281, 0.0139]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [5]:
class InteractionModule(nn.Module):
    def __init__(self, n_features):
        super(InteractionModule, self).__init__()
        self.n_features = n_features
        # Initialize a set of interaction tensors, one for the state tensor and one for each column of the transition tensor
        self.interaction_tensors = nn.ParameterList([nn.Parameter(torch_randnorm([n_features, n_features, n_features], dim = 1)) for _ in range(n_features + 1)])

    def forward(self, state_tensor, previous_transition_tensor):
        # Get batch size
        batch = state_tensor.shape[0]
        # Assuming previous_transition_tensors is a list of transition tensors from the previous step
        candidates = []
        for i in range(self.n_features + 1):
            if i == 0:  # Interaction with the state tensor
                current_tensor = state_tensor
            else:  # Interaction with columns of the previous transition tensor
                current_tensor = previous_transition_tensor[:, :, i - 1]

            interaction_tensor = self.interaction_tensors[i]
            current_tensor_expanded = current_tensor.unsqueeze(1).expand(-1, self.n_features, -1)  # Shape: [batch, n_features, n_features]
            interaction_tensor_expanded = interaction_tensor.unsqueeze(0).expand(batch, -1, -1, -1)  # Shape: [batch, n_features, n_features, n_features]
            # Multiply and sum over the last dimension to get the transition tensor
            candidate = torch.einsum('bik,bijk->bij', current_tensor_expanded, interaction_tensor_expanded)
            
            candidates.append(candidate)
            
        candidates_tensor = torch.stack(candidates, dim = -1)
        return candidates_tensor


In [6]:
class CustomLayerExtended(nn.Module):
    def __init__(self, n_features):
        super(CustomLayerExtended, self).__init__()
        self.n_features = n_features
        self.interaction_module = InteractionModule(n_features)
        self.selector_module = SelectorModule(n_features + 1)

    def forward(self, x):
        batch, length, n_features = x.size()
        output = x.new_empty(batch, length, n_features)

        # Initialize previous transition tensors (for the first step)
        # Assuming it's a list of zero tensors for simplicity
        previous_transition_tensor = torch.zeros(batch, n_features, n_features)

        for l in range(length):
            state_tensor = x[:, l, :]
            # Generate candidates
            candidates = self.interaction_module(state_tensor, previous_transition_tensor)
            # Select one candidate
            selected_transition_tensor = self.selector_module(candidates)
            # Update the previous_transition_tensors for the next iteration
            previous_transition_tensor = selected_transition_tensor
            # Compute output for this step
            output[:, l, :] = torch.matmul(selected_transition_tensor, state_tensor.unsqueeze(-1)).squeeze(-1)

        return output, selected_transition_tensor


In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SelectorModule(nn.Module):
    def __init__(self, num_slices):
        super(SelectorModule, self).__init__()
        # A simple linear layer to compute importance scores for each slice
        self.importance = nn.Linear(num_slices, num_slices)

    def forward(self, x):
        # Assuming x is of shape [batch_size, height, width, num_slices]
        batch_size, _, _, num_slices = x.shape

        # Compute importance scores by reducing x across spatial dimensions
        # Here, we take the mean of x across the spatial dimensions to get a vector per slice
        x_reduced = x.mean(dim=[1, 2])  # Shape: [batch_size, num_slices]

        # Compute scores for each slice
        scores = self.importance(x_reduced)  # Shape: [batch_size, num_slices]

        # Apply softmax to get weights for each slice
        weights = F.softmax(scores, dim=-1)  # Shape: [batch_size, num_slices]

        # Correct application of weights:
        # We need to ensure weights are applied across the num_slices dimension correctly.
        # Since weights are [batch_size, num_slices] and x is [batch_size, height, width, num_slices],
        # we permute x to bring num_slices to the front for broadcasting.
        x_permuted = x.permute(0, 3, 1, 2)  # Shape: [batch_size, num_slices, height, width]
        
        # Now, multiply by weights. We need to reshape weights to [batch_size, num_slices, 1, 1] for broadcasting.
        weighted_slices = x_permuted * weights.view(batch_size, num_slices, 1, 1)
        
        # Finally, sum the weighted slices across the num_slices dimension (now the first dimension after permute)
        selected = weighted_slices.sum(dim=1)  # Shape: [batch_size, height, width]

        return selected

# Example usage
batch_size = 10
tensor = torch.rand(batch_size, 5, 5, 6)  # Example tensor
model = SelectorModule(num_slices=6)

result = model(tensor)
print(result.shape)  # Should print torch.Size([10, 5, 5])


torch.Size([10, 5, 5])


In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class ModelWithMultiHeadAttention(nn.Module):
    def __init__(self, n_features, num_heads):
        super(ModelWithMultiHeadAttention, self).__init__()
        self.multihead_attn = nn.MultiheadAttention(embed_dim=n_features, num_heads=num_heads)
        # Optional: Additional feed-forward layers can be added here

    def forward(self, x):
        # Adjust input from shape [batch, seq_len, features] to [seq_len, batch, features]
        x = x.permute(1, 0, 2)
        
        # MultiHeadAttention expects input as (query, key, value)
        attn_output, _ = self.multihead_attn(x, x, x)
        
        # Adjust output back to [batch, seq_len, features]
        attn_output = attn_output.permute(1, 0, 2)
        
        return attn_output

# Initialize the model
n_features = 4
num_heads = 2  # The number of heads in the multi-head attention model. Adjust as needed.
model = ModelWithMultiHeadAttention(n_features=n_features, num_heads=num_heads)

# Define input dimensions
batch, length, dim = 13, 64, n_features
# Create a sample input tensor
x = torch.randn(batch, length, dim)

# Process the input through the model
y = model(x)

print(y.shape)
assert y.shape == x.shape, "Output shape does not match input shape."


torch.Size([13, 64, 4])


In [9]:
print(y)

tensor([[[-1.3132e-02,  9.6670e-05,  4.3873e-02,  3.7204e-02],
         [-7.9725e-02,  2.7489e-02,  6.3702e-02,  9.1772e-02],
         [ 9.6000e-03,  6.6347e-03,  3.0099e-02,  1.1324e-02],
         ...,
         [-9.7331e-03,  5.2403e-03,  2.2834e-02,  3.6004e-02],
         [-1.1410e-01, -1.7790e-02,  5.4972e-02,  5.3656e-02],
         [ 7.1453e-02,  7.1417e-02,  3.7364e-02,  7.4027e-02]],

        [[ 5.0169e-03, -1.8186e-02,  5.0923e-02,  6.3843e-02],
         [-6.0023e-02, -5.4565e-03,  6.3910e-02,  9.8263e-02],
         [-8.3269e-02, -1.2595e-02,  7.4005e-02,  1.1287e-01],
         ...,
         [-4.0306e-02, -4.9772e-02,  4.5456e-02,  3.4064e-02],
         [-1.6063e-01,  4.1586e-03,  8.9445e-02,  1.6022e-01],
         [-1.6493e-01, -5.8833e-02,  6.9903e-02,  6.9010e-02]],

        [[-1.1364e-02, -4.2455e-03, -6.4126e-02, -6.5738e-02],
         [ 2.0326e-03,  9.5053e-04, -2.3919e-02, -2.4569e-02],
         [-3.6914e-02, -1.1604e-02, -2.7392e-02, -2.6827e-02],
         ...,
         

# Example Training

## Simple Data Generation

In [10]:
import numpy as np
import torch

def generate_normalized_multivariate_time_series(n_features, total_length, amplitude=1.0):
    t = np.linspace(0, 100 * np.pi, total_length)
    series = np.zeros((total_length, n_features))
    for i in range(n_features):
        series[:, i] = amplitude * np.cos(t * (i + 1) / n_features) + 10
    
    # Normalize such that each timestep's values sum to 1
    series_sum = np.sum(series, axis=1, keepdims=True)
    series_normalized = series / series_sum
    
    return series_normalized

def segment_time_series(series, length):
    # Assuming series is a numpy array of shape [total_length, n_features]
    total_length, n_features = series.shape
    segments = []
    for start in range(0, total_length - length, length):
        segment = series[start:start + length]
        segments.append(segment)
    return np.stack(segments)


In [11]:
n_features = 4
length = 64  # Segment length
total_length = 1024  # Arbitrary total length for the generated series

# Generate and segment the time series
series = generate_normalized_multivariate_time_series(n_features, total_length)
series_x = series[:-1,]
series_y = series[1:,]

segments_x = segment_time_series(series_x, length)
segments_y = segment_time_series(series_y, length)

# Convert to tensors
segments_tensor_x = torch.tensor(segments_x, dtype=torch.float)
segments_tensor_y = torch.tensor(segments_y, dtype=torch.float)

# Prepare inputs and targets
X = segments_tensor_x
# Shift segments to the right by one timestep to create the targets
Y =  segments_tensor_y


In [12]:
from torch import nn, optim

# Model
num_heads = 4
model = ModelWithMultiHeadAttention(n_features=n_features, num_heads=num_heads)

# Loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
epochs = 100
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, Y)

    # Backward and optimize
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item()}')


Epoch [10/100], Loss: 0.0023037781938910484
Epoch [20/100], Loss: 0.0027160472236573696
Epoch [30/100], Loss: 0.0005753056611865759
Epoch [40/100], Loss: 0.000462029071059078
Epoch [50/100], Loss: 0.0002887541486416012
Epoch [60/100], Loss: 0.00026820178027264774
Epoch [70/100], Loss: 0.0002540374407544732
Epoch [80/100], Loss: 0.00024360966926906258
Epoch [90/100], Loss: 0.0002441710967104882
Epoch [100/100], Loss: 0.00024371060135308653


In [13]:
torch.stack([X[1,:,1],Y[1,:,1]], dim = -1)

tensor([[0.2304, 0.2339],
        [0.2339, 0.2378],
        [0.2378, 0.2419],
        [0.2419, 0.2460],
        [0.2460, 0.2497],
        [0.2497, 0.2529],
        [0.2529, 0.2553],
        [0.2553, 0.2569],
        [0.2569, 0.2577],
        [0.2577, 0.2576],
        [0.2576, 0.2570],
        [0.2570, 0.2558],
        [0.2558, 0.2545],
        [0.2545, 0.2530],
        [0.2530, 0.2518],
        [0.2518, 0.2508],
        [0.2508, 0.2502],
        [0.2502, 0.2500],
        [0.2500, 0.2503],
        [0.2503, 0.2511],
        [0.2511, 0.2522],
        [0.2522, 0.2535],
        [0.2535, 0.2549],
        [0.2549, 0.2562],
        [0.2562, 0.2572],
        [0.2572, 0.2577],
        [0.2577, 0.2575],
        [0.2575, 0.2565],
        [0.2565, 0.2546],
        [0.2546, 0.2520],
        [0.2520, 0.2486],
        [0.2486, 0.2447],
        [0.2447, 0.2406],
        [0.2406, 0.2365],
        [0.2365, 0.2327],
        [0.2327, 0.2295],
        [0.2295, 0.2269],
        [0.2269, 0.2253],
        [0.2

In [14]:
import plotly.graph_objects as go

def plot_model_output_vs_target(model_outputs, targets, batch_index=0, feature_index=0):
    # Extract the specified feature for the given batch from both the model outputs and targets
    model_output_series = model_outputs[batch_index, :, feature_index].detach().numpy()
    target_series = targets[batch_index, :, feature_index].numpy()
    
    # Create a range for the x-axis (timesteps)
    timesteps = list(range(model_output_series.shape[0]))
    
    # Create traces
    model_trace = go.Scatter(x=timesteps, y=model_output_series, mode='lines', name='Model Output')
    target_trace = go.Scatter(x=timesteps, y=target_series, mode='lines', name='Target')
    
    # Create the figure and add traces
    fig = go.Figure()
    fig.add_trace(model_trace)
    fig.add_trace(target_trace)
    
    # Add title and labels
    fig.update_layout(title=f'Model Output vs Target for Feature {feature_index}, Batch {batch_index}',
                      xaxis_title='Timestep',
                      yaxis_title='Value')
    
    # Show the figure
    fig.show()

# Assuming `y` and `Y` are your model outputs and targets, respectively
# Adjust batch_index and feature_index as needed
plot_model_output_vs_target(outputs, Y, batch_index=2, feature_index=3)


In [15]:
torch.stack([outputs[1,:,1],Y[1,:,1]], dim = -1)

tensor([[0.2509, 0.2339],
        [0.2509, 0.2378],
        [0.2509, 0.2419],
        [0.2509, 0.2460],
        [0.2509, 0.2497],
        [0.2509, 0.2529],
        [0.2509, 0.2553],
        [0.2509, 0.2569],
        [0.2509, 0.2577],
        [0.2509, 0.2576],
        [0.2509, 0.2570],
        [0.2509, 0.2558],
        [0.2509, 0.2545],
        [0.2509, 0.2530],
        [0.2509, 0.2518],
        [0.2509, 0.2508],
        [0.2509, 0.2502],
        [0.2509, 0.2500],
        [0.2509, 0.2503],
        [0.2509, 0.2511],
        [0.2509, 0.2522],
        [0.2509, 0.2535],
        [0.2509, 0.2549],
        [0.2509, 0.2562],
        [0.2509, 0.2572],
        [0.2509, 0.2577],
        [0.2509, 0.2575],
        [0.2509, 0.2565],
        [0.2509, 0.2546],
        [0.2509, 0.2520],
        [0.2509, 0.2486],
        [0.2509, 0.2447],
        [0.2509, 0.2406],
        [0.2509, 0.2365],
        [0.2509, 0.2327],
        [0.2509, 0.2295],
        [0.2509, 0.2269],
        [0.2509, 0.2253],
        [0.2