In [1]:
from coilspy import ComplexCoil

In [2]:
num_elements = 5

# Thetas for state, transition, and interactions
angles_dict = {
    'state': 0.3,
    'transition': 0.2,
    'interaction': 0.4
}

# Set restrictions

# Local
# restrict_dict = {
#     0: [2, 3, 4],
#     1: [3, 4],
#     2: [0, 4],
#     3: [0, 1],
#     4: [0, 1, 2]
# }

# Grouping
restrict_dict = {
    0: [2, 3, 4],
    1: [2, 3, 4],
    2: [0, 1],
    3: [0, 1],
    4: [0, 1]
}

# No restrictions
# restrict_dict = {}

In [3]:
test_coil = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

C:\Users\johnm\Documents\GitHub\coilsPy\coilspy\generator\generate_complex_sum.py:78: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  rotated_complex_numbers = torch.tensor(rotated_complex_numbers, dtype=torch.complex128)


In [4]:
test_coil.step_coil(renormalize=True)
probs = test_coil.get_prob()
print(probs)
print(sum(probs))
print(sum(probs[:2]))

tensor([0.3115, 0.1083, 0.1242, 0.2276, 0.2284], dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(0.4198, dtype=torch.float64)


In [5]:
save_state_tensor, save_transition_tensor, save_interaction_tensor = test_coil.state_tensor, test_coil.transition_tensor, test_coil.interaction_tensor

In [6]:
coil1 = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

coil1.state_tensor = save_state_tensor
coil1.transition_tensor = save_transition_tensor
coil1.interaction_tensor = save_interaction_tensor

In [7]:
coil2 = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

coil2.state_tensor = save_state_tensor
coil2.transition_tensor = save_transition_tensor
coil2.interaction_tensor = save_interaction_tensor

In [8]:
coil1.step_coil(renormalize=True)
print(coil1.get_prob())
coil2.step_coil(renormalize=True)
print(coil2.get_prob())


tensor([0.1563, 0.2635, 0.1182, 0.3425, 0.1195], dtype=torch.float64)
tensor([0.1563, 0.2635, 0.1182, 0.3425, 0.1195], dtype=torch.float64)
