In [263]:
from coilspy import ComplexCoil

In [264]:
num_elements = 5

# Thetas for state, transition, and interactions
angles_dict = {
    'state': 0.3,
    'transition': 0.2,
    'interaction': 0.4
}

# Set restrictions

# Local
# restrict_dict = {
#     0: [2, 3, 4],
#     1: [3, 4],
#     2: [0, 4],
#     3: [0, 1],
#     4: [0, 1, 2]
# }

# Grouping
restrict_dict = {
    0: [2, 3, 4],
    1: [2, 3, 4],
    2: [0, 1],
    3: [0, 1],
    4: [0, 1]
}

# No restrictions
# restrict_dict = {}

In [265]:
test_coil = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

In [266]:
test_coil.state_tensor.shape

torch.Size([1, 5])

In [438]:
test_coil.step_coil(renormalize=True)
probs = test_coil.get_prob()
print(probs)
print(sum(probs[0]))
print(sum(probs[0][:2]))

tensor([[0.2388, 0.0412, 0.0764, 0.4551, 0.1885]], dtype=torch.float64)
tensor(1.0000, dtype=torch.float64)
tensor(0.2800, dtype=torch.float64)


In [268]:
save_state_tensor, save_transition_tensor, save_interaction_tensor = test_coil.state_tensor, test_coil.transition_tensor, test_coil.interaction_tensor

In [269]:
coil1 = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

coil1.state_tensor = save_state_tensor
coil1.transition_tensor = save_transition_tensor
coil1.interaction_tensor = save_interaction_tensor

In [270]:
coil2 = ComplexCoil(
    num_elements=num_elements,
    angles_dict=angles_dict,
    state_center_re=0,
    state_center_im=0,
    state_sigma_re=1.0e100,
    state_sigma_im=1.0e100,
    state_magnitude_re=1.0,
    state_magnitude_im=100.0,
    state_restrictions=[],
    trans_sigma_re_lo_lim=0.2,
    trans_sigma_re_hi_lim=0.5,
    trans_sigma_im=1.0e10,
    trans_magnitude_re=1.0,
    trans_magnitude_im=1.0e5,
    trans_restrictions=restrict_dict,
    inter_sigma_re_lo_lim=0.2,
    inter_sigma_re_hi_lim=0.5,
    inter_sigma_im=1.0e10,
    inter_magnitude_re=1.0,
    inter_magnitude_im=1.0e5,
    inter_restrictions=restrict_dict,
)

coil2.state_tensor = save_state_tensor
coil2.transition_tensor = save_transition_tensor
coil2.interaction_tensor = save_interaction_tensor

In [271]:
coil1.step_coil(renormalize=True, sel_temperature=1e-5)
print(coil1.get_prob())
coil2.step_coil(renormalize=True)
print(coil2.get_prob())


tensor([[0.1344, 0.1456, 0.3585, 0.2555, 0.1060]], dtype=torch.float64)
tensor([[0.1344, 0.1456, 0.3585, 0.2555, 0.1060]], dtype=torch.float64)
